-- Seed data: tennis courts around West Lafayette / Lafayette, IN
-- Source: OpenStreetMap (via Overpass API) + Nominatim reverse geocoding, 2026-09-02
-- court_type/name are best-effort guesses (verified = false) — review and correct in the Supabase table editor.

insert into public.courts (name, address, location, court_type, surface, num_courts, lit, notes, source, external_id, verified)
values
  ('Tennis Courts – Harvey Lane', 'Harvey Lane, West Lafayette, Tippecanoe County, Indiana, 47906, United States', st_point(-86.965886, 40.470199)::geography, 'unknown', 'unknown', 4, false, 'Auto-imported from OpenStreetMap; name/type not verified — please correct if you know this location.', 'openstreetmap', 'cluster-115227619', false),
  ('Tennis Courts – Blackbird Farms Apartments', 'Kestral Boulevard, Blackbird Farms Apartments, West Lafayette, Tippecanoe County, Indiana, 47906, United States', st_point(-86.941408, 40.444977)::geography, 'private', 'unknown', 1, false, 'Auto-imported from OpenStreetMap; name/type not verified — please correct if you know this location.', 'openstreetmap', 'cluster-244599582', false),
  ('Tennis Courts – North River Road', 'North River Road, West Lafayette, Tippecanoe County, Indiana, 46906, United States', st_point(-86.899252, 40.428929)::geography, 'unknown', 'hard', 1, true, 'Auto-imported from OpenStreetMap; name/type not verified — please correct if you know this location.', 'openstreetmap', 'cluster-257177661', false),
  ('Tennis Courts – Erie Street', 'Erie Street, Lafayette, Tippecanoe County, Indiana, 47904, United States', st_point(-86.870273, 40.434588)::geography, 'unknown', 'unknown', 1, false, 'Auto-imported from OpenStreetMap; name/type not verified — please correct if you know this location.', 'openstreetmap', 'cluster-257177665', false),
  ('Tennis Courts – Kingfisher Drive', 'Kingfisher Drive, Lafayette, Tippecanoe County, Indiana, 47909, United States', st_point(-86.871591, 40.362342)::geography, 'unknown', 'unknown', 2, false, 'Auto-imported from OpenStreetMap; name/type not verified — please correct if you know this location.', 'openstreetmap', 'cluster-264466454', false),
  ('Tennis Courts – Gregory Avenue', 'Gregory Avenue, Lafayette, Tippecanoe County, Indiana, 47905, United States', st_point(-86.869641, 40.398515)::geography, 'unknown', 'unknown', 10, false, 'Auto-imported from OpenStreetMap; name/type not verified — please correct if you know this location.', 'openstreetmap', 'cluster-264497086', false),
  ('Tennis Courts – Pheasant Run', 'Eagles Way Drive, Pheasant Run, Lafayette, Tippecanoe County, Indiana, 47909, United States', st_point(-86.860788, 40.384029)::geography, 'private', 'unknown', 2, false, 'Auto-imported from OpenStreetMap; name/type not verified — please correct if you know this location.', 'openstreetmap', 'cluster-264497106', false),
  ('Tennis Courts – Meadowbrook', 'Goldersgreen Drive, Meadowbrook, Tippecanoe County, Indiana, 47905, United States', st_point(-86.805031, 40.422265)::geography, 'unknown', 'unknown', 2, false, 'Auto-imported from OpenStreetMap; name/type not verified — please correct if you know this location.', 'openstreetmap', 'cluster-264517604', false),
  ('Tennis Courts – Purdue Outer XC Trail', 'Purdue Outer XC Trail, West Lafayette, Tippecanoe County, Indiana, 47907, United States', st_point(-86.938344, 40.436024)::geography, 'public', 'unknown', 13, false, 'Auto-imported from OpenStreetMap; name/type not verified — please correct if you know this location. On Purdue University property — may require Purdue ID or reservation.', 'openstreetmap', 'cluster-283069988', false),
  ('Tennis Courts – Avondale', 'Avondale Street, Avondale, West Lafayette, Tippecanoe County, Indiana, 47906, United States', st_point(-86.908919, 40.461578)::geography, 'unknown', 'unknown', 10, false, 'Auto-imported from OpenStreetMap; name/type not verified — please correct if you know this location.', 'openstreetmap', 'cluster-283539039', false),
  ('Tennis Courts – Cumberland Avenue', 'Cumberland Avenue, West Lafayette, Tippecanoe County, Indiana, 47906, United States', st_point(-86.941467, 40.458093)::geography, 'unknown', 'unknown', 1, false, 'Auto-imported from OpenStreetMap; name/type not verified — please correct if you know this location.', 'openstreetmap', 'cluster-369597828', false),
  ('Tennis Courts – Beck Lane', 'Beck Lane, Lafayette, Tippecanoe County, Indiana, 47909, United States', st_point(-86.886563, 40.387487)::geography, 'unknown', 'unknown', 5, false, 'Auto-imported from OpenStreetMap; name/type not verified — please correct if you know this location.', 'openstreetmap', 'cluster-475216721', false),
  ('Tennis Courts – Sycamore Street', 'Sycamore Street, Lafayette, Tippecanoe County, Indiana, 47902, United States', st_point(-86.902594, 40.407793)::geography, 'unknown', 'hard', 1, false, 'Auto-imported from OpenStreetMap; name/type not verified — please correct if you know this location.', 'openstreetmap', 'cluster-547097677', false),
  ('Tennis Courts – Purdue University', 'Purdue University, 610, West Lafayette, Tippecanoe County, Indiana, 47907, United States', st_point(-86.924976, 40.428450)::geography, 'public', 'unknown', 6, false, 'Auto-imported from OpenStreetMap; name/type not verified — please correct if you know this location. On Purdue University property — may require Purdue ID or reservation.', 'openstreetmap', 'cluster-551306779', false),
  ('Tennis Courts – Chatham Square', 'Green Acres Drive, Chatham Square, Lafayette, Tippecanoe County, Indiana, 47905, United States', st_point(-86.847913, 40.431452)::geography, 'private', 'unknown', 1, false, 'Auto-imported from OpenStreetMap; name/type not verified — please correct if you know this location.', 'openstreetmap', 'cluster-673505860', false),
  ('Tennis Courts – McQuinn Estates', 'Fawn Ridge Drive, McQuinn Estates, Tippecanoe County, Indiana, 47906, United States', st_point(-86.963395, 40.433477)::geography, 'private', 'unknown', 1, false, 'Auto-imported from OpenStreetMap; name/type not verified — please correct if you know this location.', 'openstreetmap', 'cluster-874194600', false),
  ('Tennis Courts – Autumn Lane North', 'Autumn Lane North, Tippecanoe County, Indiana, 47909, United States', st_point(-86.901611, 40.349937)::geography, 'unknown', 'unknown', 3, false, 'Auto-imported from OpenStreetMap; name/type not verified — please correct if you know this location.', 'openstreetmap', 'cluster-885972716', false),
  ('Tennis Courts – Burberry Drive North', 'Burberry Drive North, Lafayette, Tippecanoe County, Indiana, 47905, United States', st_point(-86.836619, 40.401358)::geography, 'unknown', 'unknown', 1, false, 'Auto-imported from OpenStreetMap; name/type not verified — please correct if you know this location.', 'openstreetmap', 'cluster-992525471', false),
  ('Tennis Courts – Margesson Crossing', 'Margesson Crossing, Tippecanoe County, Indiana, 47909, United States', st_point(-86.852310, 40.355686)::geography, 'private', 'unknown', 1, false, 'Auto-imported from OpenStreetMap; name/type not verified — please correct if you know this location.', 'openstreetmap', 'cluster-1043276457', false),
  ('Tennis Courts – Flowermound Drive', 'Flowermound Drive, Tippecanoe County, Indiana, 47906, United States', st_point(-86.911857, 40.497295)::geography, 'unknown', 'hard', 10, false, 'Auto-imported from OpenStreetMap; name/type not verified — please correct if you know this location.', 'openstreetmap', 'cluster-1144239939', false),
  ('Tennis Courts – Rockland Drive', 'Rockland Drive, West Lafayette, Tippecanoe County, Indiana, 47906, United States', st_point(-86.905261, 40.437970)::geography, 'unknown', 'unknown', 2, false, 'Auto-imported from OpenStreetMap; name/type not verified — please correct if you know this location.', 'openstreetmap', 'cluster-1478709221', false),
  ('Tennis Courts – Salem Courthouse Apartments', '3114, Courthouse Drive East, Salem Courthouse Apartments, West Lafayette, Tippecanoe County, Indiana, 47906, United States', st_point(-86.926639, 40.462185)::geography, 'private', 'unknown', 4, true, 'Auto-imported from OpenStreetMap; name/type not verified — please correct if you know this location.', 'openstreetmap', 'cluster-1480162171', false),
  ('Tennis Courts – Chauncey Village Apartments', 'North Chauncey Court, Chauncey Village Apartments, Lafayette, Tippecanoe County, Indiana, 47905, United States', st_point(-86.847527, 40.433939)::geography, 'private', 'unknown', 2, true, 'Auto-imported from OpenStreetMap; name/type not verified — please correct if you know this location.', 'openstreetmap', 'cluster-1480162902', false)
on conflict (source, external_id) where external_id is not null do nothing;
